language: go

services:
  - docker

go:
  - 1.12.x

git:
  depth: 1

before_install:
  - ./exec install

install: true

script:
  - ./exec test

after_script:
  - docker login -u _ -p "$HEROKU_TOKEN"  registry.heroku.com
  - ./exec publish

deploy:
  provider: script
  script: ./exec release

branches:
  only:
    - master


