#!/bin/bash

case $1 in
    "install")
        make install -f ./build/Makefile
    ;;

    "build")
        make build -f ./build/Makefile -B
    ;;

    "test")
        export CONFIG_FILE="$PWD/test.env"
        go test -v -race ./...
    ;;

    "run")
        if [[ $2 == "build" ]]; then
        	docker run -p 8080:8080 lanago:latest
        else
            export CONFIG_FILE="$PWD/dev.env"
        	go run -v main.go
        fi
    ;;

    "publish")
    	make publish -f ./build/Makefile -B
    ;;

    "release")
    	make release -f ./build/Makefile -B
    ;;

    *)
        echo "Invalid action, you sould run one of the following options:"
        echo
        echo "  - build"
        echo "  - test"
        echo "  - run [ build ]"
    ;;
esac